### ISSUE TITLE
Provide jpg output 

### ISSUE THREAD

**Issue by yannxaver** [yoavbls/web-chaos-graph#1]
I'm sure many people have found their new wallpaper when they first saw this image...

I've tried converting the svg with a couple of tools but they all failed. Would be nice if a jpeg output was provided by default.

**Comment by yoavbls** [comment]
I added a PNG output since Excalidraw doesn't have a built in option for JPG. Is it okay?
lol, I didn't think it'd be requested as wallpaper. 
I recommend this though:  
  
![New Project (10)](https://github.com/user-attachments/assets/624dcb5c-441d-4430-b1b9-0ae7302819a4)

**Comment by yannxaver** [comment]
Thank you
